### ISSUE TITLE
socat problem (E read(6, 0xb2be90, 8192): Permission denied)

### ISSUE THREAD

**Issue by rocknrollarmy** [BasterdOperator/IPv4-to-IPv6-Only-Portmapper#2]
HI,

erst einmal Danke für das Zusammenfassen der benötigten Schritte. Ziemlich hilfreich wenn man versucht sich im IPv6 / DS-Lite Dschungel zurecht zu finden.

Ich bin wie hier beschrieben vorgegangen. Die Verbindung vom Client zum Uberspace funktioniert auch. Allerdings bekomme ich dann einen Fehler von `socat`. Hier mal der Output.

```
[xxx@xxx ~]$ ~/bin/socat -d -d UDP4-LISTEN:63530,fork UDP6:MYHOST:1194
2017/12/26 21:35:22 socat[15190] N listening on UDP AF=2 0.0.0.0:63530
2017/12/26 21:38:31 socat[15190] N accepting UDP connection from AF=2 xx.xxx.xxx.xx:9761
2017/12/26 21:38:31 socat[15190] N forked off child process 5451
2017/12/26 21:38:31 socat[15190] N listening on UDP AF=2 0.0.0.0:63530
2017/12/26 21:38:31 socat[5451] N opening connection to AF=10 [2a02:xxx:xxx:xxx:xxx:xxx:xxx:xxx]:1194
2017/12/26 21:38:31 socat[5451] N successfully connected from local address AF=10 [2001:1a50:xxx:xxx:xxx:xxx:xxxx:xxxx]:52168
2017/12/26 21:38:31 socat[5451] N starting data transfer loop with FDs [5,5] and [6,6]
2017/12/26 21:38:31 socat[5451] E read(6, 0xb2be90, 8192): Permission denied
2017/12/26 21:38:31 socat[5451] N exit(1)
2017/12/26 21:38:31 socat[15190] N childdied(): handling signal 17
```
Die reine UDP Verbindung zu meinem Raspberry scheint ja zumindest zu funktionieren. 

Spontan irgendeine Idee wo es hier klemmen könnte?

**Comment by BasterdOperator** [comment]
Sorry @rocknrollarmy für die späte Antwort. Leider habe ich da gerade keine schlaue Antwort.  :-( 
Nur Generell: Falls Du gleichzeitig zu dem hier erklärten PortMapper ein neues openvpn gebaut hast und nicht 100% sicher bist, ob es jetzt am PortMapper oder OpenVPN liegt, könntest Du natürlich nach dem Ausschlussprinzip erst einmal etwas "einfacheres" Tunneln, wie SSH/Port 22.

**Comment by BasterdOperator** [comment]
close
